
#include <stdio.h>

int main(void) {
    // CGI 환경의 필수적인 HTTP 헤더를 출력합니다.
    // Content-Type을 text/html로 설정하여 브라우저에 HTML 문서임을 알립니다.
    printf("Content-Type: text/html\n\n");

    // HTML 문서의 시작을 출력합니다.
    printf("<!DOCTYPE html>\n");
    printf("<html lang=\"ko\">\n");
    printf("<head>\n");
    printf("    <meta charset=\"UTF-8\">\n");
    printf("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    printf("    <title>아날로그 사운드의 소울</title>\n");

    // CSS 스타일을 출력합니다.
    printf("    <style>\n");
    printf("        @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;700&display=swap');\n");
    printf("        \n");
    printf("        body {\n");
    printf("            font-family: 'Noto Sans KR', sans-serif;\n");
    printf("            background-color: #f0f0f0;\n");
    printf("            color: #333;\n");
    printf("            line-height: 1.6;\n");
    printf("            margin: 0;\n");
    printf("            padding: 40px 20px;\n");
    printf("            display: flex;\n");
    printf("            flex-direction: column;\n");
    printf("            justify-content: center;\n");
    printf("            align-items: center;\n");
    printf("            min-height: 100vh;\n");
    printf("            text-align: center;\n");
    printf("        }\n");
    printf("        .header-section {\n");
    printf("            display: flex;\n");
    printf("            align-items: center;\n");
    printf("            justify-content: center;\n");
    printf("            gap: 20px; /* 아이콘 간의 간격 */\n");
    printf("            margin-bottom: 20px;\n");
    printf("        }\n");
    printf("        .header-image-main {\n");
    printf("            width: 150px;\n");
    printf("            height: 150px;\n");
    printf("            border-radius: 50%;\n");
    printf("            object-fit: cover;\n");
    printf("            cursor: pointer;\n");
    printf("            border: 4px solid #00796b;\n");
    printf("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);\n");
    printf("            transition: transform 0.3s ease;\n");
    printf("        }\n");
    printf("        .header-image-main:hover {\n");
    printf("            transform: scale(1.05);\n");
    printf("        }\n");
    printf("        .header-image-sub {\n");
    printf("            width: 100px; /* 서브 아이콘 크기 조정 */\n");
    printf("            height: 100px;\n");
    printf("            border-radius: 50%;\n");
    printf("            object-fit: cover;\n");
    printf("            cursor: pointer;\n");
    printf("            border: 3px solid #e65100; /* 다른 강조 색상 */\n");
    printf("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);\n");
    printf("            transition: transform 0.3s ease;\n");
    printf("        }\n");
    printf("        .header-image-sub:hover {\n");
    printf("            transform: scale(1.05);\n");
    printf("        }\n");
    printf("        .container {\n");
    printf("            max-width: 800px;\n");
    printf("            padding: 30px;\n");
    printf("            background-color: #ffffff;\n");
    printf("            border-radius: 12px;\n");
    printf("            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);\n");
    printf("            border: 1px solid #ddd;\n");
    printf("            margin-bottom: 20px;\n");
    printf("        }\n");
    printf("        h1 {\n");
    printf("            color: #00796b;\n");
    printf("            font-weight: 700;\n");
    printf("            font-size: 2.5em;\n");
    printf("            margin-bottom: 20px;\n");
    printf("        }\n");
    printf("        p {\n");
    printf("            font-size: 1.1em;\n");
    printf("            font-weight: 300;\n");
    printf("            margin-bottom: 20px;\n");
    printf("        }\n");
    printf("        .highlight {\n");
    printf("            color: #e65100;\n");
    printf("            font-weight: 700;\n");
    printf("        }\n");
    printf("        .list-container {\n");
    printf("            margin-top: 30px;\n");
    printf("            display: flex;\n");
    printf("            justify-content: space-around;\n");
    printf("            flex-wrap: wrap;\n");
    printf("            gap: 20px;\n");
    printf("        }\n");
    printf("        .list-item {\n");
    printf("            background-color: #fafafa;\n");
    printf("            padding: 15px;\n");
    printf("            border-radius: 8px;\n");
    printf("            width: 45%;\n");
    printf("            box-sizing: border-box;\n");
    printf("            border-left: 3px solid #00796b;\n");
    printf("            text-align: left;\n");
    printf("        }\n");
    printf("        .list-item h3 {\n");
    printf("            color: #333;\n");
    printf("            margin: 0 0 10px;\n");
    printf("            font-weight: 400;\n");
    printf("            font-size: 1.2em;\n");
    printf("        }\n");
    printf("        .list-item ul {\n");
    printf("            list-style: none;\n");
    printf("            padding: 0;\n");
    printf("            margin: 0;\n");
    printf("        }\n");
    printf("        .list-item li {\n");
    printf("            margin-bottom: 5px;\n");
    printf("            font-size: 0.95em;\n");
    printf("        }\n");
    printf("        .banner-container {\n");
    printf("            display: flex;\n");
    printf("            justify-content: center;\n");
    printf("            gap: 20px;\n");
    printf("            margin-top: 30px;\n");
    printf("            flex-wrap: wrap;\n");
    printf("        }\n");
    printf("        .banner-container img {\n");
    printf("            max-width: 45%;\n");
    printf("            height: auto;\n");
    printf("            border-radius: 8px;\n");
    printf("            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n");
    printf("            cursor: pointer;\n");
    printf("            transition: transform 0.3s ease;\n");
    printf("        }\n");
    printf("        .banner-container img:hover {\n");
    printf("            transform: scale(1.03);\n");
    printf("        }\n");
    printf("        .footer-info {\n");
    printf("            margin-top: 40px;\n");
    printf("            padding: 20px;\n");
    printf("            background-color: #f0f0f0;\n");
    printf("            border-top: 1px solid #ddd;\n");
    printf("            color: #666;\n");
    printf("            font-size: 0.9em;\n");
    printf("        }\n");
    printf("        .footer-info p {\n");
    printf("            margin: 5px 0;\n");
    printf("        }\n");
    printf("    </style>\n");
    printf("</head>\n");

    // HTML Body를 출력합니다.
    printf("<body>\n");
    printf("    <audio id=\"audio1\" src=\"your-audio-file.mp3\" preload=\"auto\"></audio>\n");
    printf("    <audio id=\"audio2\" src=\"your-audio-file2.mp3\" preload=\"auto\"></audio>\n");
    printf("    <audio id=\"audio3\" src=\"your-audio-file3.mp3\" preload=\"auto\"></audio>\n");
    printf("\n");
    printf("    <div class=\"header-section\">\n");
    printf("        <img src=\"https://placehold.co/100x100/E65100/FFFFFF?text=Mix\" alt=\"믹스 오디오\" class=\"header-image-sub\" onclick=\"playAudio('audio1')\">\n");
    printf("        <img src=\"https://placehold.co/150x150/00796B/FFFFFF?text=Main+Audio\" alt=\"메인 오디오\" class=\"header-image-main\" onclick=\"playAudio('audio2')\">\n");
    printf("        <img src=\"https://placehold.co/100x100/E65100/FFFFFF?text=Blues\" alt=\"블루스 오디오\" class=\"header-image-sub\" onclick=\"playAudio('audio3')\">\n");
    printf("    </div>\n");
    printf("\n");
    printf("    <div class=\"container\">\n");
    printf("        <h1>아날로그 사운드의 소울, 앰프와 기타가 만나는 곳</h1>\n");
    printf("        <p>\n");
    printf("            진공관의 따뜻한 불빛처럼, 블루스 기타의 깊은 선율처럼, 아날로그 사운드를 향한 우리의 열정이 모여 하나의 앰프 회로를 완성하는 공간입니다. 여기는 단순히 회로도를 공유하고 연주 팁을 나누는 것을 넘어, 손끝에서 탄생하는 진정한 소리의 즐거움을 함께 만들어가는 커뮤니티입니다.\n");
    printf("        </p>\n");
    printf("        <p>\n");
    printf("            기술적인 탐구와 예술적인 연주가 만나는 이곳에서, 나만의 사운드 <span class=\"highlight\">톤(Tone)</span>을 찾아가는 여정을 시작해 보세요. 궁금했던 회로의 원리부터, 소울 가득한 연주를 위한 <span class=\"highlight\">블루스 스케일(Blues Scale)</span> 연습까지, 당신의 열정을 채워줄 모든 것을 함께 나눕니다.\n");
    printf("        </p>\n");
    printf("        <p>\n");
    printf("            모두가 앰프 빌더이자 기타리스트인 우리들의 아지트에서, 당신의 <span class=\"highlight\">오디오 소울(Audio Soul)</span>을 깨워보세요.\n");
    printf("        </p>\n");
    printf("        \n");
    printf("        <div class=\"list-container\">\n");
    printf("            <div class=\"list-item\">\n");
    printf("                <h3>주요 활동</h3>\n");
    printf("                <ul>\n");
    printf("                    <li>앰프 회로 제작 및 설계 토론</li>\n");
    printf("                    <li>DIY 오디오 프로젝트 공유</li>\n");
    printf("                    <li>블루스 기타 연주 팁 및 노하우</li>\n");
    printf("                    <li>장비 리뷰 및 추천</li>\n");
    printf("                </ul>\n");
    printf("            </div>\n");
    printf("            <div class=\"list-item\">\n");
    printf("                <h3>누구를 위한 공간인가요?</h3>\n");
    printf("                <ul>\n");
    printf("                    <li>자신만의 앰프를 만들고 싶은 분</li>\n");
    printf("                    <li>블루스 기타 연주에 깊이 빠져있는 분</li>\n");
    printf("                    <li>아날로그 사운드를 사랑하는 분</li>\n");
    printf("                    <li>같은 취미를 가진 사람들과 소통하고 싶은 분</li>\n");
    printf("                </ul>\n");
    printf("            </div>\n");
    printf("        </div>\n");
    printf("    </div>\n");
    printf("\n");
    printf("    <div class=\"banner-container\">\n");
    printf("     <a href=\"#\"><img src=\"/1.jpg\" alt=\"pip49.com\"></a>\n"); 
    printf("        <a href=\"#\"><img src=\"https://placehold.co/400x150/E65100/FFFFFF?text=Banner+2\" alt=\"배너 2\"></a>\n");
    printf("    </div>\n");
    printf("\n");
    printf("    <div class=\"footer-info\">\n");
    printf("        <p>상호명: [사업자명]</p>\n");
    printf("        <p>대표자: [대표자명]</p>\n");
    printf("        <p>주소: [주소]</p>\n");
    printf("        <p>전화번호: [전화번호]</p>\n");
    printf("        <p>이메일: [이메일]</p>\n");
    printf("    </div>\n");
    printf("\n");
    printf("    <script>\n");
    printf("        var audio1 = document.getElementById('audio1');\n");
    printf("        var audio2 = document.getElementById('audio2');\n");
    printf("        var audio3 = document.getElementById('audio3');\n");
    printf("        var currentAudio = null;\n");
    printf("\n");
    printf("        function playAudio(audioId) {\n");
    printf("            var audio = document.getElementById(audioId);\n");
    printf("\n");
    printf("            // 다른 오디오가 재생 중이면 정지\n");
    printf("            if (currentAudio && currentAudio !== audio) {\n");
    printf("                currentAudio.pause();\n");
    printf("                currentAudio.currentTime = 0;\n");
    printf("            }\n");
    printf("\n");
    printf("            if (audio.paused) {\n");
    printf("                audio.play();\n");
    printf("                currentAudio = audio;\n");
    printf("            } else {\n");
    printf("                audio.pause();\n");
    printf("            }\n");
    printf("        }\n");
    printf("    </script>\n");
    printf("</body>\n");
    printf("</html>\n");

    return 0;
}
